### ISSUE TITLE
How to config markup heaviness in test.py?

### ISSUE THREAD

**Issue by zzmao** [huangzhikun1995/IPM-Net#4]
How to specify the markup heaviness in the result?

Are different train models needed for different level of markup heaviness?

Thanks!

**Comment by huangzhikun1995** [comment]
A controlled degree of makeup can be achieved using the pre-trained model.
You can change the value of  'level' defined in line 129 of `test.py` from 0 to 1 to control the makeup level of the generated image.

**Comment by zzmao** [comment]
Thanks! @huangzhikun1995
